version: "2"

linters:
  default: all
  disable:
    - depguard
    - godot
    - exhaustruct
    - funlen
    - noinlineerr

  settings:
    perfsprint:
      string-format: false

  exclusions:
    rules:
      - linters:
          - revive
        text: "package-comments.*"
